/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-21 17:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Parcial;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Principal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<h1 class=\"text-center\">Bienvenidos al Sistema de Gestión de Incidencias</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-xs-12 col-sm-6 col-md-6 col-lg-3\">\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("\t\t\ttempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("\t\t\tquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\tconsequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("\t\t\tcillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("\t\t\tproident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
