/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2016-07-05 03:13:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Seguimiento;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Seguimiento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<style>\n");
      out.write("#seguimiento {\n");
      out.write("\tbackground-color: #fff;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: auto;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar consumoService = [ {\n");
      out.write("\t\tcodIncidencia : \"INA001\",\n");
      out.write("\t\tfIncidencia : \"10-01-2014\",\n");
      out.write("\t\tiEstado : 1\n");
      out.write("\t}, {\n");
      out.write("\t\tcodIncidencia : \"INA002\",\n");
      out.write("\t\tfIncidencia : \"12-06-2014\",\n");
      out.write("\t\tiEstado : 2\n");
      out.write("\t}, {\n");
      out.write("\t\tcodIncidencia : \"INA003\",\n");
      out.write("\t\tfIncidencia : \"14-03-2015\",\n");
      out.write("\t\tiEstado : 4\n");
      out.write("\t}, {\n");
      out.write("\t\tcodIncidencia : \"INA004\",\n");
      out.write("\t\tfIncidencia : \"05-11-2015\",\n");
      out.write("\t\tiEstado : 3\n");
      out.write("\t} ];\n");
      out.write("\n");
      out.write("\tfor (var i = 1; i < consumoService.length; i++) {\n");
      out.write("\t\tvar objeto = consumoService[i];\n");
      out.write("\t\tconsole.log(objeto);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction cargar(id) {\n");
      out.write("\t\tvar Canvas = new objeto(id);\n");
      out.write("\t\tCanvas.cargarCanvas();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tvar objeto = function(id) {\n");
      out.write("\t\tvar elemento = document.getElementById(id);\n");
      out.write("\t\tvar activo = \"#fff\";\n");
      out.write("\t\tvar inactivo = \"#ccc\";\n");
      out.write("\t\tvar bordes = \"#ccc\";\n");
      out.write("\t\tvar fillactive = \"#FF920F\";\n");
      out.write("\t\tvar fillinactive = \"#fff\";\n");
      out.write("\t\tvar fillinactivepaso=\"#96968F\";\n");
      out.write("\t\tvar inactivepaso=\"#fff\";\n");
      out.write("\t\tvar colorLetra = \"#737167\";\n");
      out.write("\t\tvar iEstado = 2;\n");
      out.write("\t\tthis.size = {\n");
      out.write("\t\t\twidth : elemento.offsetWidth,\n");
      out.write("\t\t\theight : elemento.offsetHeight\n");
      out.write("\t\t};\n");
      out.write("\t\tthis.cargarCanvas = function() {\n");
      out.write("\t\t\tif (elemento.getContext(\"2d\")) {\n");
      out.write("\t\t\t\tlienzo = elemento.getContext(\"2d\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 1 ? fillactive : iEstado > 1 ? fillinactivepaso : fillinactive ;\n");
      out.write("\t\t\t\tlienzo.strokeStyle = bordes;\n");
      out.write("\t\t\t\tlienzo.arc(100, 100, 40, 0, Math.PI * 2, true);\n");
      out.write("\t\t\t\tlienzo.lineTo(250, 100);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.stroke();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 2 ? fillactive : iEstado > 2 ? fillinactivepaso : fillinactive;\n");
      out.write("\t\t\t\tlienzo.arc(300, 100, 40, 0, Math.PI * 2, true);\n");
      out.write("\t\t\t\tlienzo.lineTo(450, 100);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.stroke();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 3 ? fillactive : iEstado > 3 ? fillinactivepaso : fillinactive;\n");
      out.write("\t\t\t\tlienzo.arc(500, 100, 40, 0, Math.PI * 2, true);\n");
      out.write("\t\t\t\tlienzo.lineTo(650, 100);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.stroke();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 4 ? fillactive : iEstado > 3 ? fillinactivepaso : fillinactive;\n");
      out.write("\t\t\t\tlienzo.arc(700, 100, 40, 0, Math.PI * 2, true);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.stroke();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\t/*Buenas*/\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 1 ? activo : iEstado > 1 ? inactivepaso : inactivo;\n");
      out.write("\t\t\t\tlienzo.moveTo(120, 85);\n");
      out.write("\t\t\t\tlienzo.lineTo(95, 115);\n");
      out.write("\t\t\t\tlienzo.lineTo(85, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(90, 100);\n");
      out.write("\t\t\t\tlienzo.lineTo(95, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(115, 85);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 2 ? activo : iEstado > 2 ? inactivepaso : inactivo;\n");
      out.write("\t\t\t\tlienzo.moveTo(320, 85);\n");
      out.write("\t\t\t\tlienzo.lineTo(295, 115);\n");
      out.write("\t\t\t\tlienzo.lineTo(285, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(290, 100);\n");
      out.write("\t\t\t\tlienzo.lineTo(295, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(315, 85);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 3 ? activo : iEstado > 3 ? inactivepaso : inactivo;\n");
      out.write("\t\t\t\tlienzo.moveTo(520, 85);\n");
      out.write("\t\t\t\tlienzo.lineTo(495, 115);\n");
      out.write("\t\t\t\tlienzo.lineTo(485, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(490, 100);\n");
      out.write("\t\t\t\tlienzo.lineTo(495, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(515, 85);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = iEstado == 4 ? activo : iEstado > 4 ? inactivepaso : inactivo;\n");
      out.write("\t\t\t\tlienzo.moveTo(720, 85);\n");
      out.write("\t\t\t\tlienzo.lineTo(695, 115);\n");
      out.write("\t\t\t\tlienzo.lineTo(685, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(690, 100);\n");
      out.write("\t\t\t\tlienzo.lineTo(695, 105);\n");
      out.write("\t\t\t\tlienzo.lineTo(715, 85);\n");
      out.write("\t\t\t\tlienzo.fill();\n");
      out.write("\t\t\t\tlienzo.closePath();\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.beginPath();\n");
      out.write("\t\t\t\tlienzo.fillStyle = colorLetra;\n");
      out.write("\t\t\t\tlienzo.font = \"16px Calibri Light\";\n");
      out.write("\t\t\t\tlienzo.fillText(\"Creado\", 75, 175);\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.font = \"16px Calibri Light\";\n");
      out.write("\t\t\t\tlienzo.fillText(\"Observado\", 268, 175);\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.font = \"16px Calibri Light\";\n");
      out.write("\t\t\t\tlienzo.fillText(\"En proceso\", 467, 175);\n");
      out.write("\n");
      out.write("\t\t\t\tlienzo.font = \"16px Calibri Light\";\n");
      out.write("\t\t\t\tlienzo.fillText(\"Finalizado\", 670, 175);\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\talert(\"El canvas no soporta\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t};\n");
      out.write("</script>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("\t<h3>\n");
      out.write("\t\t<i class=\"fa fa-line-chart\" aria-hidden=\"true\"></i> Seguimiento\n");
      out.write("\t</h3>\n");
      out.write("\t<hr>\n");
      out.write("\t<br>\n");
      out.write("\t<section class=\"row animated fadeIn\">\n");
      out.write("<!-- \tzoomIn -->\n");
      out.write("\t\t<article>\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-3 col-md-4 col-lg-4\">\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t<small>Incidencia Nro : 00001</small>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<th>Estado</th>\n");
      out.write("\t\t\t\t\t\t\t\t<th>Fecha</th>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Creado</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>03/05/2016 03:24:08 pm</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Observador</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>03/05/2016 03:28:51 pm</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>En proceso</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>03/05/2016 03:31:01 pm</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Finalizado</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>03/05/2016 03:50:51 pm</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-9 col-md-8 col-lg-8\">\n");
      out.write("\t\t\t\t<canvas id=\"seguimiento\" width=\"800\" height=\"300\">\n");
      out.write("\t\t\t\tSu navegador no soporta el elemento html5\n");
      out.write("\t\t\t</canvas>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</article>\n");
      out.write("\t</section>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tvar Canvas = new objeto(\"seguimiento\");\n");
      out.write("\t\tCanvas.cargarCanvas();\n");
      out.write("\t</script>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
