/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-02 22:29:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Seguimiento;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Seguimiento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<style>\r\n");
      out.write("#seguimiento {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar objeto = function(id) {\r\n");
      out.write("\t\tvar elemento = document.getElementById(id);\r\n");
      out.write("\t\tvar activo = \"#fff\";\r\n");
      out.write("\t\tvar inactivo = \"#ccc\";\r\n");
      out.write("\t\tvar bordes = \"#ccc\";\r\n");
      out.write("\t\tvar fillactive = \"#FF920F\";\r\n");
      out.write("\t\tvar fillinactive = \"#fff\";\r\n");
      out.write("\t\tthis.size = {\r\n");
      out.write("\t\t\twidth : elemento.offsetWidth,\r\n");
      out.write("\t\t\theight : elemento.offsetHeight\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tthis.cargarCanvas = function() {\r\n");
      out.write("\t\t\tif (elemento.getContext(\"2d\")) {\r\n");
      out.write("\t\t\t\tlienzo = elemento.getContext(\"2d\");\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = fillactive;\r\n");
      out.write("\t\t\t\tlienzo.strokeStyle = bordes;\r\n");
      out.write("\t\t\t\tlienzo.arc(100, 100, 40, 0, Math.PI * 2, true);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(250, 100);\r\n");
      out.write("\t\t\t\tlienzo.fill();\r\n");
      out.write("\t\t\t\tlienzo.closePath();\r\n");
      out.write("\t\t\t\tlienzo.stroke();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = fillactive;\r\n");
      out.write("\t\t\t\tlienzo.arc(300, 100, 40, 0, Math.PI * 2, true);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(450, 100);\r\n");
      out.write("\t\t\t\tlienzo.closePath();\r\n");
      out.write("\t\t\t\tlienzo.stroke();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = fillactive;\r\n");
      out.write("\t\t\t\tlienzo.arc(500, 100, 40, 0, Math.PI * 2, true);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(650, 100);\r\n");
      out.write("\t\t\t\tlienzo.closePath();\r\n");
      out.write("\t\t\t\tlienzo.stroke();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = fillactive;\r\n");
      out.write("\t\t\t\tlienzo.arc(700, 100, 40, 0, Math.PI * 2, true);\r\n");
      out.write("\t\t\t\tlienzo.closePath();\r\n");
      out.write("\t\t\t\tlienzo.stroke();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t/*Buenas*/\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = activo;\r\n");
      out.write("\t\t\t\tlienzo.moveTo(120, 85);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(95, 115);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(85, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(90, 100);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(95, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(115, 85);\r\n");
      out.write("\t\t\t\tlienzo.fill();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = inactivo;\r\n");
      out.write("\t\t\t\tlienzo.moveTo(320, 85);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(295, 115);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(285, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(290, 100);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(295, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(315, 85);\r\n");
      out.write("\t\t\t\tlienzo.fill();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = inactivo;\r\n");
      out.write("\t\t\t\tlienzo.moveTo(520, 85);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(495, 115);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(485, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(490, 100);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(495, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(515, 85);\r\n");
      out.write("\t\t\t\tlienzo.fill();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.beginPath();\r\n");
      out.write("\t\t\t\tlienzo.fillStyle = inactivo;\r\n");
      out.write("\t\t\t\tlienzo.moveTo(720, 85);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(695, 115);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(685, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(690, 100);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(695, 105);\r\n");
      out.write("\t\t\t\tlienzo.lineTo(715, 85);\r\n");
      out.write("\t\t\t\tlienzo.fill();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.strokeStyle = \"red\";\r\n");
      out.write("\t\t\t\tlienzo.font = \"bold 15px Calibri Light\";\r\n");
      out.write("\t\t\t\tlienzo.fillText(\"Creado\", 75, 175);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.font = \"bold 15px Calibri Light\";\r\n");
      out.write("\t\t\t\tlienzo.fillText(\"Observado\", 275, 175);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.font = \"bold 15px Calibri Light\";\r\n");
      out.write("\t\t\t\tlienzo.fillText(\"En proceso\", 475, 175);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tlienzo.font = \"bold 15px Calibri Light\";\r\n");
      out.write("\t\t\t\tlienzo.fillText(\"Finalizado\", 675, 175);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"El canvas no soporta\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<h3>\r\n");
      out.write("\t\t<i class=\"fa fa-line-chart\" aria-hidden=\"true\"></i> Seguimiento\r\n");
      out.write("\t</h3>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<section class=\"row animated zoomIn\">\r\n");
      out.write("\t\t<div id=\"main\" class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\r\n");
      out.write("\t\t\t<canvas id=\"seguimiento\" width=\"800\" height=\"300\">\r\n");
      out.write("\t\t\t\tSu navegador no soporta el elemento html5\r\n");
      out.write("\t\t\t</canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar Canvas = new objeto(\"seguimiento\");\r\n");
      out.write("\t\tCanvas.cargarCanvas();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t// \t\twindow.addEventListener(\"resize\", handleResize);\r\n");
      out.write("\t\t// \t\tfunction handleResize() {\r\n");
      out.write("\t\t// \t\t\tvar w = window.innerWidth - 2; // -2 accounts for the border\r\n");
      out.write("\t\t// \t\t\tvar h = window.innerHeight - 2;\r\n");
      out.write("\t\t// \t\t\tCanvas.width = w;\r\n");
      out.write("\t\t// \t\t\tCanvas.height = h;\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\tvar ratio = 100 / 100; // 100 is the width and height of the circle content.\r\n");
      out.write("\t\t// \t\t\tvar windowRatio = w / h;\r\n");
      out.write("\t\t// \t\t\tvar scale = w / 100;\r\n");
      out.write("\t\t// \t\t\tif (windowRatio > ratio) {\r\n");
      out.write("\t\t// \t\t\t\tscale = h / 100;\r\n");
      out.write("\t\t// \t\t\t}\r\n");
      out.write("\t\t// \t\t\t// Scale up to fit width or height\r\n");
      out.write("\t\t// \t\t\tc.scaleX = c.scaleY = scale;\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\t// Center the shape\r\n");
      out.write("\t\t// \t\t\tc.x = w / 2;\r\n");
      out.write("\t\t// \t\t\tc.y = h / 2;\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\t\t// \t    stage.update();\r\n");
      out.write("\t\t// \t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// \t\thandleResize();\r\n");
      out.write("// \t\t$(document).ready(function() {\r\n");
      out.write("// \t\t\t//Get the canvas &\r\n");
      out.write("// \t\t\tvar c = $('#seguimiento');\r\n");
      out.write("// \t\t\tvar ct = c.get(0).getContext('2d');\r\n");
      out.write("// \t\t\tvar container = $(c).parent();\r\n");
      out.write("\r\n");
      out.write("// \t\t\t//Run function when browser resizes\r\n");
      out.write("// \t\t\t$(window).resize(respondCanvas);\r\n");
      out.write("\r\n");
      out.write("// \t\t\tfunction respondCanvas() {\r\n");
      out.write("// \t\t\t\tc.attr('width', $(container).width()); //max width\r\n");
      out.write("// \t\t\t\tc.attr('height', $(container).height()); //max height\r\n");
      out.write("// \t\t\t}\r\n");
      out.write("// \t\t\t//Initial call \r\n");
      out.write("// \t\t\trespondCanvas();\r\n");
      out.write("\r\n");
      out.write("// \t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
